title: Retreat, Rejuvenate and Reset
description: Welcome to the wellness retreat at the Bougainvillea Boutique Villa in Sri Lanka. It is a 5-day, 4-night experience in front of the beach of Weligama, from 1st to 5th November. The property is safe, secure, and designed for relaxation and rejuvenation.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman